// Generated by scripts/fetch-disclosures.mjs — do not edit by hand.
// Source: the API's /v1/disclosures/* endpoints. Refresh with `npm run disclosures:sync`.
// The base used is deliberately not recorded here: it is an environment, and
// recording it would make the file churn when the same documents are pulled
// from dev instead of prod.

export interface DisclosureMeta {
  title: string
  version: string
  updatedAt: string
}

export const disclosures = {
  'terms-of-use': { title: "Terms of Use", version: "1.0.0", updatedAt: "2026-08-14" },
  'privacy-policy': { title: "Privacy Policy", version: "1.0.0", updatedAt: "2026-08-14" },
  'acknowledgement': { title: "Acknowledgement", version: "1.1.0", updatedAt: "2026-09-16" },
} satisfies Record<string, DisclosureMeta>
